###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: hospital-memcached

    mailhog:
      image: mailhog/mailhog:latest
      container_name: hospital-mailhog
      ports:
        - "8081:8025"

    redis:
      image: redis:alpine
      container_name: hospital-redis

    mysql:
      image: mysql:8.0
      container_name: hospital-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=root
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root
      ports:
        - "8082:3306"

    mariadb:
      image: mariadb:10.4
      container_name: hospital-mariadb
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=root
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root
      ports:
        - "8083:3306"

    postgres:
      image: postgres:11.1-alpine
      container_name: hospital-postgres
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=root
      ports:
        - "8084:5432"

    elasticsearch:
      image: elasticsearch:6.5.4
      container_name: hospital-elasticsearch

    webserver:
      image: nginx:alpine
      container_name: hospital-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: hospital-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

